### ISSUE TITLE
Logger not appear on macOS High Sierra

### ISSUE THREAD

**Issue by mohdaminyuddin** [spring-projects/spring-ide#196]
Hi guys,

I just updated to macOS High Sierra yesterday, it seems like the logger is invisible in the console but System.out is printed correctly. I can simply copy the log and paste in any text editor to read it. But not directly from console.

Log appear in the console as following :
<img width="1365" alt="screen shot 2017-09-29 at 16 22 39" src="https://user-images.githubusercontent.com/300463/31007371-fa82a0f8-a532-11e7-8582-f05a9a4f8908.png">

Pasted in atom as following :
<img width="974" alt="screen shot 2017-09-29 at 16 30 37" src="https://user-images.githubusercontent.com/300463/31007570-8f52825c-a533-11e7-8bb0-2f092067718b.png">

I tried to run STS in other machine (running same macOS as high sierra) also having the issue as well.

p/s : reinstall & creating new workspace doesn't help.

**Comment by martinlippert** [comment]
I can reproduce this issue with macOS High Sierra running on a virtual machine, too. The workaround for this is to disable the "ANSI Console" in the console view. You should also disable the "ANSI Console Output" in the launch config for the boot app to avoid ansi color codes showing up in the console.

If you want a more permanent solution, you can uninstall the Ansi Console Plugin altogether from your STS installation (via the `About dialog -> Installation Details -> Installed Software`).

**Comment by mohdaminyuddin** [comment]
Thanks @martinlippert. Uninstall the `Ansi Console Plugin` works well for me.

**Comment by paulvi** [comment]
No need to uninstall.

There is icon to enable/disable

![1](https://user-images.githubusercontent.com/1614482/31015218-8ec1435a-a551-11e7-82ba-a6773afee2be.PNG)

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

I debugged into this and it looks like a problem in SWT to me, therefore filed: https://bugs.eclipse.org/bugs/show_bug.cgi?id=525383

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

This is not going to be fixed in STS 3.9.1 due to lack of feedback and not enough time to get this sorted for the STS 3.9.1 timeframe.

As a consequence, the ANSI coloring plugin will NOT be included in the STS 3.9.1 distribution by default. You can still install it yourself from the Eclipse Marketplace. And we will bring it back into future versions as soon as the issue with macOS 10.13 is solved.

**Comment by paulvi** [comment]
While not just having it disabled?

And it should be disabled only if macOS >= 10.13

well, the result will be that more users witll know about https://github.com/mihnita/ansi-econsole project

**Comment by martinlippert** [comment]
The question is where to disable what on macOS >= 10.13
Since this is a combination of the Spring Boot app being launched with a specific option and the console plugin being installed and enabled, the question is where to disable all this on macOS 10.13 and allow people to get it back once there is a fixed version available.

Contributions welcome... :-)

**Comment by martinlippert** [comment]
Okay, I implemented an auto-disable into the boot launch support that prevents boot apps from being launched with the ANSI coloring option when the IDE is running on macOS High Sierra (10.13). We need to delete this piece of code again once the problem with the ANSI console got fixed.

**Comment by chinaerserver** [comment]
i mark on the "SHOW THE escapesequence" options  ,ansi console print colorful output right now!!!I like colorful log very much!

**Comment by martinlippert** [comment]
This seems indeed to work again, so I will go ahead and enable the option in the launch config again.

**Comment by martinlippert** [comment]
Done...

**Comment by rafatuita** [comment]
@martinlippert Martin I updated my Studio and even downloaded a new one just now (http://download.springsource.com/release/STS/3.9.2.RELEASE/dist/e4.7/spring-tool-suite-3.9.2.RELEASE-e4.7.2-macosx-cocoa-x86_64.dmg).

I made sure Espace Sequences are enabled (which came by default by the way on this new install) and I still cannot see my console output colored as it is supposed to.

When I deploy it (using maven) and run it through Putty, I can see the colors but not through Studio. here are the versions:

```
Spring Studio: Version: 3.9.2.RELEASE
Build Id: 201712210947
Platform: Eclipse Oxygen.2 (4.7.2)
```

```
Spring IDE
Version: 3.9.2.201712210913-RELEASE
```

```
Eclipse Platform
Version: 4.7.2.v20171130-0510
Build id: M20171130-0510
```

```
macOS High Sierra
  System Version:	macOS 10.13.2 (17C205)
  Kernel Version:	Darwin 17.3.0
  Boot Volume:	Untitled 1
  Boot Mode:	Normal
  Computer Name:	admin’s MacBook Pro
  User Name:	rafael (admin)
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	3:11

```

**Comment by martinlippert** [comment]
Since we don't enable this by default in STS 3.9.2 (we do this again in STS 3.9.3), you have to enable the color output in Spring Boot manually by adding a VM arg: `-Dspring.output.ansi.enabled=always`

**Comment by rafatuita** [comment]
great! adding that to each of my boot configuration works. thanks @martinlippert

**Comment by thestevenbell** [comment]
This issue is occurring again with macOS Mojave Version 10.14.1. Configuring the Ansi Console to show escape sequences fixes the problem.
